### PR TITLE
Prevent json parsing errors from failing silently

### LINKED ISSUE #16: JSON parse errors fail silently
This issue details the problem pretty well:
https://github.com/essential-projects/bootstrapper_node/issues/1

Currently the dir scanner just uses an empty object when a JSON parse error occurs. This leads to misbehavior that can not be identified during bootstrapping with the current implementation.

I would like to suggest not to catch the error, but let it happen without intervention.

### PR DESCRIPTION
**Pull request by ElRaptorus**
Closes #16 

When parsing a config file fails, the error is no longer swallowed, but rethrown with additional information as to which file caused the error.

### CODE REVIEW

File: lib/dir_scanner.js [hunk 1]
```diff
@@ -15,7 +15,7 @@ function readFile(filename, vars) {
     const items = JSON.parse(newContent);
     return items;
   } catch (error) {
-    return {};
+    throw new Error(`couldn't parse package.json at '${filename}': ${parseError.message}`);
```
Comment (heikomat) [inline lib/dir_scanner.js]: You copy-pasted an old version of my suggestion from the issue (i updated my comment since then). The config file is probably not a `package.json`, and the error-object isn't called `parseError` here. This would be more correct:

```JavaScript
throw new Error(`couldn't parse JSON-file at '${filename}': ${error.message}`);
```

**Comment by ElRaptorus** [comment]
@heikomat done

**Comment by ElRaptorus** [comment]
@moellenbeck Ok, so I gather we don't do this with `npm version ` like we do in the process-engine projects?

**Comment by ElRaptorus** [comment]
@moellenbeck This is the Process-Engine Script I was talking about yesterday:
https://github.com/process-engine/process_engine_meta/blob/develop/_sample_scripts/update_to_1.0.0-rc1.sh

basically, we always use this when we want to publish one or more packages, *after* we merged everything to `develop`. 
`npm version` takes care of setting the package number, creating tags for that version and pushing them.
https://docs.npmjs.com/cli/version
